### PR TITLE
Specify embedded Hebrew xml:lang; update expectations (#7).

### LINKED ISSUE #7: Update direction test and expectations.
Add xml:lang to embedded Hebrew text.
Update expectations for direction test and other tests due to TTPE updates.

### PR DESCRIPTION
**Pull request by skynavga**
Closes #7.

### CODE REVIEW

**Review by palemieux — DISMISSED** [review]
How are the following two issues related?

* addition of `xml:lang`
* update to expectations

**Comment by skynavga** [comment]
@palemieux

- ttml1-prstn-break - fix rendering logic in ttpe; former expectation bad; see also https://github.com/skynav/ttt/issues/299
- ttml1-prstn-direction - partially fix rendering logic in ttpe; former expectation bad; see also https://github.com/skynav/ttt/issues/297
- ttml1-prstn-font-family - shouldn't have been updated at this time, will remove from PR; but see also https://github.com/skynav/ttt/issues/296, which fix will update this expectation
- ttml1-prstn-font-size-anamorphic-cell - svg rendering artifact difference only
- ttml1-prstn-font-size-anamorphic-em - svg rendering artifact difference only
- ttml1-prstn-font-size-inherited-em - fix rendering logic in ttpe; former expectation bad; see also https://github.com/skynav/ttt/issues/300

_svg rendering artifact difference only_ refers to changes in ttpe that generate different svg outputs while still retaining the same visual result; these are housekeeping updates that keep the expectations synchronized with ttpe

**Comment by skynavga** [comment]
Removed erroneously updated expectation noted above in https://github.com/w3c/ttml1-tests/pull/8#issuecomment-891808465.

**Comment by skynavga** [comment]
@palemieux any further comment or change requested?

**Comment by palemieux** [comment]
@skynavga Can you provide a PNG of the expected results, to remove the SVG rendered from the chain?

**Comment by skynavga** [comment]
@palemieux re: https://github.com/w3c/ttml1-tests/pull/8#issuecomment-893085702, in theory yes, but in practice no; I would be happy to explain my reasons in a ttwg call;

**Comment by skynavga** [comment]
@palemieux to elaborate a bit:

- there are at present 190 `*.expected.zip` files in the [w3c/ttml1-tests](https://github.com/w3c/ttml1-tests) and [w3c/ttml1-tests](https://github.com/w3c/ttml2-tests) repositories, all of which would have to be converted, or 190 additional `*.png.expected.zip` files added, a substantial project that would require sponsorship;
- the current expectation files were provided by Skynav to the group when these two repositories were populated for exemplar purposes only and for use as evidence of some (non-normative) rendering for implementation reports;
- the current README.md files of both this repository [w3c/ttml1-tests](https://github.com/w3c/ttml1-tests) and [w3c/ttml1-tests](https://github.com/w3c/ttml2-tests) include the following text:
>For tests having primarily visual presentation semantics, each presentation test is associated with a like named ZIP archive with the suffix `.expected.zip`, which contains the output of a particular reference implementation (TTPE). Each such reference archive contains a manifest file and one or more image frames represented in some image format. In the present form of the reference archives, the image format is `image/svg+xml`. These image frames should not be construed as normative, but merely serve as a possible reference image for performing (human visual) comparisons of expected output.
- the use of PNG files as an alternative to SVG effectively makes some SVG renderer implementation a dependency, at least with respect to using TTPE;
- at present the SVG renderer used by TTPE is Apache Batik, which is quite dated and almost entirely unmaintained, meaning that I don't trust it as a normative renderer; using an alternative SVG renderer would require revision of TTPE, a substantial project that would require sponsorship, and the result would still be to have such alternative renderer as a dependency;
- the original (and current) requirement for use of the expectation files w.r.t. TTPE is to enable regression testing that is independent of SVG rendering, i.e., independent of actual pixel output; therefore, changing to PNG renderings would abrogate this requirement;
- finally, if you are asking me to provide an extra-exemplary rendering of a particular SVG output from TTPE, for discussion purposes only (i..e., not to go into the repository), then I could arrange for that; I would simple use Chrome to render the SVG and then take a screen shot of the results on my MacOS laptop; then again, you (or anyone) can already do this without my help;

**Pull request merged**
